# Author: Xing Li
# Org: Fortinet
# Date: 2020.10.13
# Label: package
# Desc: Configure DNAT policies.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure DNAT policies.
     fmgr_pkg_central_dnat:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        pkg: ansible
        state: present
        pkg_central_dnat:
           name: 'ansible-test-dnat' # DNAT policy has dependency with virtual IP, name must be same with a name in Virtual IPs