# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: DNS
# Desc: FortiGuard DNS domain filters

- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: FortiGuard DNS domain filters.
     fmgr_dnsfilter_profile_ftgddns_filters:
        bypass_validation: False
        adom: ansible
        profile: 'ansible-test' # name
        state: present
        dnsfilter_profile_ftgddns_filters:
           action: monitor
          #  category: <value of string>
           id: 1
           log: disable