# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: firewall
# Desc: Configure service groups.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure service groups.
     fmgr_firewall_service_group:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_service_group:
           color: 1
           comment: 'ansible-comment'
          #  member: ['DNS']
           name: 'ansible-test-group'
           proxy: disable