# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall
# Desc: Configure shaping profiles.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure shaping profiles.
     fmgr_firewall_shapingprofile:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_shapingprofile:
           comment: 'ansible-comment'
          #  default-class-id: <value of integer>
           profile-name: 'ansible-test'
          #  shaping-entries:
          #    -
          #        class-id: <value of integer>
          #        guaranteed-bandwidth-percentage: <value of integer>
          #        id: <value of integer>
          #        maximum-bandwidth-percentage: <value of integer>
          #        priority: <value in [low, medium, high]>