# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: firewall, IPv6
# Desc: Configure IPv6 firewall addresses

- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv6 firewall addresses.
     fmgr_firewall_address6:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_address6:
          #  cache-ttl: <value of integer>
          #  color: <value of integer>
          #  comment: <value of string>
          #  dynamic_mapping:
          #    -
          #        _scope:
          #          -
          #              name: <value of string>
          #              vdom: <value of string>
          #        cache-ttl: <value of integer>
          #        color: <value of integer>
          #        comment: <value of string>
          #        end-ip: <value of string>
          #        fqdn: <value of string>
          #        host: <value of string>
          #        host-type: <value in [any, specific]>
          #        ip6: <value of string>
          #        obj-id: <value of string>
          #        sdn: <value in [nsx]>
          #        start-ip: <value of string>
          #        tags: <value of string>
          #        template: <value of string>
          #        type: <value in [ipprefix, iprange, nsx, ...]>
          #        uuid: <value of string>
          #        visibility: <value in [disable, enable]>
          #  end-ip: <value of string>
          #  fqdn: <value of string>
          #  host: <value of string>
           host-type: any #<value in [any, specific]>
           ip6: '::/55'
          #  list:
          #    -
          #        ip: <value of string>
           name: 'ansible-test'
          #  obj-id: <value of string>
          #  sdn: <value in [nsx]>
          #  start-ip: <value of string>
          #  subnet-segment:
          #    -
          #        name: <value of string>
          #        type: <value in [any, specific]>
          #        value: <value of string>
          #  tagging:
          #    -
          #        category: <value of string>
          #        name: <value of string>
          #        tags: <value of string>
          #  template: <value of string>
          #  type: <value in [ipprefix, iprange, nsx, ...]>
          #  uuid: <value of string>
           visibility: disable