# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall,IPv4
# Desc: Configure IPv4 virtual IP groups.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv4 virtual IP groups.
     fmgr_firewall_vipgrp:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_vipgrp:
           color: 2
           comments: 'ansible-test-vipgrp'
          #  dynamic_mapping:
          #    -
          #        _scope:
          #          -
          #              name: <value of string>
          #              vdom: <value of string>
          #        color: <value of integer>
          #        comments: <value of string>
          #        interface: <value of string>
          #        member: <value of string>
          #        uuid: <value of string>
          #  interface: <value of string>
           member: 'ansible-test-vip'
           name: 'ansible-test-vipgrp'
          #  uuid: <value of string>