# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: IPv6
# Desc: Retrieve all the IPv6 IP pools
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the IPv6 IP pools
     fmgr_fact:
       facts:
           selector: 'firewall_ippool6'
           params:
               adom: 'ansible'
               ippool6: ''