# Author: Xing Li
# Org: Fortinet
# Date: 2020.10.13
# Label: system
# Desc: Configure Azure network interface.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure Azure network interface.
     fmgr_system_sdnconnector_nic:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        sdn-connector: ansible-test-sdn # name
        state: present
        system_sdnconnector_nic: # available only when type is set to 'azure' in sdn-connector
          #  ip:
          #    -
          #        name: ansible-test-nicip
          #        public-ip: 222.222.22.1
           name: ansible-test-nic