# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system
# Desc: TACACS+ server entry configuration.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: TACACS+ server entry configuration.
     fmgr_system_admin_tacacs:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        state: present
        system_admin_tacacs:
           authen-type: auto #<value in [auto, ascii, pap, ...]>
           authorization: disable
           key: fortinet
           name: ansible-test-tacacs
           port: 1
          #  secondary-key: <value of string>
          #  secondary-server: <value of string>
           server: ansible
          #  tertiary-key: <value of string>
          #  tertiary-server: <value of string>