# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system
# Desc: Configure radius.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure radius.
     fmgr_system_admin_radius:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        state: present
        system_admin_radius:
           auth-type: pap #<value in [any, pap, chap, ...]>
           name: ansible-test-radius
          #  nas-ip: <value of string>
           port: 1812
          #  secondary-secret: <value of string>
          #  secondary-server: <value of string>
          #  secret: <value of string>
           server: 'ALL'