# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: package, firewall, IPv6
# Desc: Configure IPv6 interface policies.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv6 interface policies.
     fmgr_pkg_firewall_interfacepolicy6:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        pkg: ansible # package name
        state: present
        pkg_firewall_interfacepolicy6:
           address-type: ipv6 #<value in [ipv4, ipv6]>
          #  application-list: <value of string>
          #  application-list-status: <value in [disable, enable]>
          #  av-profile: <value of string>
          #  av-profile-status: <value in [disable, enable]>
           comments: ansible-comment
          #  dlp-sensor: <value of string>
          #  dlp-sensor-status: <value in [disable, enable]>
          #  dsri: <value in [disable, enable]>
          #  dstaddr6: <value of string>
           interface: ansible-interface
          #  ips-sensor: <value of string>
          #  ips-sensor-status: <value in [disable, enable]>
          #  label: <value of string>
          #  logtraffic: <value in [disable, all, utm]>
           policyid: 1
          #  scan-botnet-connections: <value in [disable, block, monitor]>
          #  service6: <value of string>
          #  spamfilter-profile: <value of string>
          #  spamfilter-profile-status: <value in [disable, enable]>
          #  srcaddr6: <value of string>
           status: enable
          #  webfilter-profile: <value of string>
          #  webfilter-profile-status: <value in [disable, enable]>