# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: snmp
# Desc: Configure IPv4 SNMP managers (hosts)

- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv4 SNMP managers (hosts).
     fmgr_devprof_system_snmp_community_hosts:
        bypass_validation: False
        adom: ansible
        devprof: 'ansible-test' # system template name, could find it in FortiManager UI: Device Manager --> Provisioning Templates --> System Templates
        community: '1' # id
        state: present
        devprof_system_snmp_community_hosts:
           ha-direct: enable
           host-type: query
           id: 1
          #  ip: <value of string>
          #  source-ip: <value of string>