# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: internet service
# Desc: Retrieve all the disable entries in the custom internet service
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the disable entries in the custom internet service
     fmgr_fact:
       facts:
           selector: 'firewall_internetservicecustom_disableentry'
           params:
               adom: 'ansible'
               internet-service-custom: 'ansible-test' # name
               disable-entry: ''