# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall, IPv4, IPv6
# Desc: Real servers.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Real servers.
     fmgr_firewall_vip46_realservers:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        vip46: 'ansible-test-vip46' # name
        state: present
        firewall_vip46_realservers:
          #  client-ip: <value of string>
           healthcheck: disable
          #  holddown-interval: <value of integer>
           id: 1
          #  ip: <value of string>
          #  max-connections: <value of integer>
          #  monitor: <value of string>
          #  port: <value of integer>
          #  status: <value in [active, standby, disable]>
          #  weight: <value of integer>