# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: package, firewall, IPv6
# Desc: Configure IPv6 policies.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv6 policies.
     fmgr_pkg_firewall_policy6:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        pkg: ansible # package name
        state: present
        pkg_firewall_policy6:
           action: accept #<value in [deny, accept, ipsec, ...]>
          #  app-category: <value of string>
          #  application: <value of integer>
          #  application-list: <value of string>
          #  auto-asic-offload: <value in [disable, enable]>
          #  av-profile: <value of string>
           comments: ansible-comment
          #  custom-log-fields: <value of string>
          #  devices: <value of string>
          #  diffserv-forward: <value in [disable, enable]>
          #  diffserv-reverse: <value in [disable, enable]>
          #  diffservcode-forward: <value of string>
          #  diffservcode-rev: <value of string>
          #  dlp-sensor: <value of string>
          #  dscp-match: <value in [disable, enable]>
          #  dscp-negate: <value in [disable, enable]>
          #  dscp-value: <value of string>
          #  dsri: <value in [disable, enable]>
           dstaddr: all
          #  dstaddr-negate: <value in [disable, enable]>
           dstintf: any
          #  firewall-session-dirty: <value in [check-all, check-new]>
          #  fixedport: <value in [disable, enable]>
          #  global-label: <value of string>
          #  groups: <value of string>
          #  icap-profile: <value of string>
          #  inbound: <value in [disable, enable]>
          #  ippool: <value in [disable, enable]>
          #  ips-sensor: <value of string>
          #  label: <value of string>
          #  logtraffic: <value in [disable, enable, all, ...]>
          #  logtraffic-start: <value in [disable, enable]>
          #  mms-profile: <value of string>
           name: ansible-test-policy6
           nat: disable
          #  natinbound: <value in [disable, enable]>
          #  natoutbound: <value in [disable, enable]>
          #  np-accelation: <value in [disable, enable]>
          #  outbound: <value in [disable, enable]>
          #  per-ip-shaper: <value of string>
           policyid: 1
          #  poolname: <value of string>
          #  profile-group: <value of string>
          #  profile-protocol-options: <value of string>
          #  profile-type: <value in [single, group]>
          #  replacemsg-override-group: <value of string>
          #  rsso: <value in [disable, enable]>
           schedule: always
          #  send-deny-packet: <value in [disable, enable]>
           service: ALL
          #  service-negate: <value in [disable, enable]>
          #  session-ttl: <value of integer>
          #  spamfilter-profile: <value of string>
           srcaddr: all
          #  srcaddr-negate: <value in [disable, enable]>
           srcintf: any
          #  ssl-mirror: <value in [disable, enable]>
          #  ssl-mirror-intf: <value of string>
          #  ssl-ssh-profile: <value of string>
           status: disable
          #  tags: <value of string>
          #  tcp-mss-receiver: <value of integer>
          #  tcp-mss-sender: <value of integer>
          #  tcp-session-without-syn: <value in [all, data-only, disable]>
          #  timeout-send-rst: <value in [disable, enable]>
          #  traffic-shaper: <value of string>
          #  traffic-shaper-reverse: <value of string>
          #  url-category: <value of string>
          #  users: <value of string>
          #  utm-status: <value in [disable, enable]>
          #  uuid: <value of string>
          #  vlan-cos-fwd: <value of integer>
          #  vlan-cos-rev: <value of integer>
          #  voip-profile: <value of string>
          #  vpntunnel: <value of string>
          #  webfilter-profile: <value of string>