# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall
# Desc: Config object tagging.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Config object tagging.
     fmgr_firewall_proxyaddrgrp_tagging:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        proxy-addrgrp: 'ansible-name' # name
        state: present
        firewall_proxyaddrgrp_tagging:
           category: 'ansible-category' # need a valid category name
           name: 'ansible-test'
           tags: ['ansible2', 'ansible1']