# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall
# Desc: Config global Wildcard FQDN address groups.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Config global Wildcard FQDN address groups.
     fmgr_firewall_wildcardfqdn_group:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_wildcardfqdn_group:
           color: 1
           comment: 'ansible-comment'
           member: 'ansible-test'
           name: 'ansible-test-fqdn-grp'
          #  uuid: <value of string>
          #  visibility: <value in [disable, enable]>