# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: FortiCarrier
# Desc: Carrier end point black/white list tables
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Carrier end point black/white list tables.
     fmgr_firewall_carrierendpointbwl:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: FortiCarrier # This is FOC-only object, need a FortiCarrier adom
        state: present
        firewall_carrierendpointbwl:
           comment: 'ansible-test'
          #  entries:
          #    -
          #        action:
          #          - block
          #          - exempt
          #          - exempt-mass-mms
          #        carrier-endpoint: <value of string>
          #        log-action:
          #          - archive
          #          - intercept
          #        pattern-type: <value in [wildcard, regexp, simple]>
          #        status: <value in [disable, enable]>
           id: 1
           name: 'ansible-test'