# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system
# Desc: List of SQL text search index fields.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: List of SQL text search index fields.
     fmgr_system_sql_tsindexfield:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        state: present
        system_sql_tsindexfield:
           category: FGT-dns
           value: ''