# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: DNS
# Desc: Retrieve all the filters in the profile

- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the filters in the profile
     fmgr_fact:
       facts:
           selector: 'dnsfilter_profile_ftgddns_filters'
           params:
               adom: 'ansible'
               profile: 'ansible-test' # name
               filters: ''