# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: 
# Desc: Retrieve all the custom application signatures
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the custom application signatures
     fmgr_fact:
       facts:
           selector: 'application_custom'
           params:
               adom: 'ansible'
               custom: ''