# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: system
# Desc: Retrieve all the workflow approval matrixs
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the workflow approval matrixs
     fmgr_fact:
       facts:
           selector: 'system_workflow_approvalmatrix'
           params:
               approval-matrix: ''
                
               