# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: firewall, IPv4
# Desc: Configure dynamic mappings of IPv4 address group
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure dynamic mappings of IPv4 address group
     fmgr_firewall_addrgrp_dynamicmapping:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        addrgrp: 'ansible' # name
        state: present
        firewall_addrgrp_dynamicmapping:
           _scope:
             -
                 name: FGT_AWS # need a valid device name
                 vdom: root # need a valid vdom name under the device
           allow-routing: disable
           color: 1
          #  comment: 'ansible-test'
          #  exclude: disable
          #  exclude-member: <value of string>
           member: 'ansible-test'
          #  tags: 'ansible1'
          #  uuid: <value of string>
           visibility: enable