# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: firewall, IPv6
# Desc: Retrieve all the taggings in the IPv6 address

- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the taggings in the IPv6 address
     fmgr_fact:
       facts:
           selector: 'firewall_address6_tagging'
           params:
               adom: 'ansible'
               address6: 'ansible-test' # name
               tagging: ''