# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall
# Desc: Retrieve all the servers to exempt from SSL inspection
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the servers to exempt from SSL inspection
     fmgr_fact:
       facts:
           selector: 'firewall_sslsshprofile_sslexempt'
           params:
               adom: 'ansible'
               ssl-ssh-profile: 'ansible-test' # name
               ssl-exempt: ''