# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall, IPv6
# Desc: Select the real servers that this server load balancing VIP will distribute traffic to.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Select the real servers that this server load balancing VIP will distribute traffic to.
     fmgr_firewall_vip6_realservers:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        vip6: 'ansible-test-vip6' # name
        state: present
        firewall_vip6_realservers:
          #  client-ip: <value of string>
           healthcheck: disable #<value in [disable, enable, vip]>
          #  holddown-interval: <value of integer>
          #  http-host: <value of string>
           id: 1
          #  ip: <value of string>
          #  max-connections: <value of integer>
          #  monitor: <value of string>
          #  port: <value of integer>
           status: active #<value in [active, standby, disable]>
          #  weight: <value of integer>