# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system
# Desc: List of device filter.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: List of device filter.
     fmgr_system_logfetch_clientprofile_devicefilter:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        client-profile: 1 # id
        state: present
        system_logfetch_clientprofile_devicefilter:
           adom: root
           device: terraform # need a valid device name
           id: 1
           vdom: terraform # need a valid vdom name