# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: snmp
# Desc: Retrieve all the hosts in the community

- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the hosts in the community
     fmgr_fact:
       facts:
           selector: 'devprof_system_snmp_community_hosts'
           params:
               adom: 'ansible'
               devprof: 'ansible-test' # system template name, could find it in FortiManager UI: Device Manager --> Provisioning Templates --> System Templates
               community: '1'
               hosts: ''