# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: package, firewall, IPv4
# Desc: Configure multicast NAT policies.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure multicast NAT policies.
     fmgr_pkg_firewall_multicastpolicy:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        pkg: ansible # package name
        state: present
        pkg_firewall_multicastpolicy:
           action: accept #<value in [deny, accept]>
          #  auto-asic-offload: <value in [disable, enable]>
          #  dnat: <value of string>
           dstaddr: all
           dstintf: any
          #  end-port: <value of integer>
           id: 2
          #  logtraffic: <value in [disable, enable]>
          #  protocol: <value of integer>
          #  snat: <value in [disable, enable]>
          #  snat-ip: <value of string>
           srcaddr: all
           srcintf: any
          #  start-port: <value of integer>
           status: disable