# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: multicast-address, IPv6
# Desc: Configure IPv6 multicast address
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv6 multicast address.
     fmgr_firewall_multicastaddress6:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_multicastaddress6:
           color: 2
           comment: 'ansible-comment'
           ip6: '2001::10/128'
           name: 'ansible-test'
          #  tagging:
          #    -
          #        category: <value of string>
          #        name: <value of string>
          #        tags: <value of string>
           visibility: enable