# Author: Xing Li
# Org: Fortinet
# Date: 2020.10.13
# Label: package
# Desc: Retrieve all the DNAT policies
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: Retrieve all the DNAT policies
     fmgr_fact:
       facts:
           selector: 'pkg_central_dnat'
           params:
               adom: 'ansible'
               pkg: 'ansible'
               dnat: ''