# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall
# Desc: Web proxy address group configuration.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Web proxy address group configuration.
     fmgr_firewall_proxyaddrgrp:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_proxyaddrgrp:
           color: 1
           comment: 'ansible-comment'
           member: 'ansible-test' # need a valid proxy address name
           name: 'ansible-test'
          #  tagging:
          #    -
          #        category: <value of string>
          #        name: <value of string>
          #        tags: <value of string>
          #  type: <value in [src, dst]>
          #  uuid: <value of string>
          #  visibility: <value in [disable, enable]>