# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: user
# Desc: Retrieve all the LDAP Groups of FSSO active directory server
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the LDAP Groups of FSSO active directory server
     fmgr_fact:
       facts:
           selector: 'user_fssopolling_adgrp'
           params:
               adom: 'ansible'
               fsso-polling: 1 # id
               adgrp: '' 
               