# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: FortiCarrier, GTP
# Desc: IP policy
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: IP policy.
     fmgr_firewall_gtp_ippolicy:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: FortiCarrier # This is FOC-only object, need a FortiCarrier adom
        gtp: 'ansible-test' # name
        state: present
        firewall_gtp_ippolicy:
           action: allow #<value in [allow, deny]>
          #  dstaddr: <value of string>
           id: 3
          #  srcaddr: <value of string>