# Author: Xing Li
# Org: Fortinet
# Date: 2020.10.13
# Label: system
# Desc: Retrieve all the Azure route tables
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the Azure route tables
     fmgr_fact:
       facts:
           selector: 'system_sdnconnector_routetable' # available only when type is set to 'azure' in sdn-connector
           params:
               adom: 'ansible'
               sdn-connector: 'ansible-test-sdn'  # name
               route-table: ''