# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system, IPv4
# Desc: Allow hosts configuration.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Allow hosts configuration.
     fmgr_system_snmp_community_hosts:
        bypass_validation: True
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        community: 1 # id
        state: present
        system_snmp_community_hosts:
           id: 1
           interface: port1
           ip: '222.222.222.3/32'