# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall, IPv6
# Desc: Configure IPv6 virtual IP groups.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv6 virtual IP groups.
     fmgr_firewall_vipgrp6:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_vipgrp6:
           color: 2
           comments: 'ansible-comment'
           member: 'ansible-test-vip6'
           name: 'ansible-test-vipgrp6'
          #  uuid: <value of string>