# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system
# Desc: User group.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: User group.
     fmgr_system_admin_group:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        state: present
        system_admin_group:
           name: 'ansible-group'
           member:
            -
              name: 'ansible-test-radius' # Member name are from Remote Authentication Server; GUI path: System Settings --> Admin --> Remote Authentication Server