# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: firewall, IPv6
# Desc: Configure dynamic mappings of virtual IP for IPv6
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure dynamic mappings of virtual IP for IPv6
     fmgr_firewall_vip6_dynamicmapping:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        vip6: 'ansible-test-vip6' # name
        state: absent
        firewall_vip6_dynamicmapping:
           _scope:
             -
                 name: FGT_AWS # need a valid device name
                 vdom: root # need a valid vdom name under the device
           arp-reply: disable
           color: 1
           comment: 'ansible-comment'
          #  extip: <value of string>
          #  extport: <value of string>
          #  http-cookie-age: <value of integer>
          #  http-cookie-domain: <value of string>
          #  http-cookie-domain-from-host: <value in [disable, enable]>
          #  http-cookie-generation: <value of integer>
          #  http-cookie-path: <value of string>
          #  http-cookie-share: <value in [disable, same-ip]>
          #  http-ip-header: <value in [disable, enable]>
          #  http-ip-header-name: <value of string>
          #  http-multiplex: <value in [disable, enable]>
          #  https-cookie-secure: <value in [disable, enable]>
           id: 1
          #  ldb-method: <value in [static, round-robin, weighted, ...]>
          #  mappedip: <value of string>
          #  mappedport: <value of string>
          #  max-embryonic-connections: <value of integer>
          #  monitor: <value of string>
          #  outlook-web-access: <value in [disable, enable]>
          #  persistence: <value in [none, http-cookie, ssl-session-id]>
          #  portforward: <value in [disable, enable]>
          #  protocol: <value in [tcp, udp, sctp]>
          #  server-type: <value in [http, https, ssl, ...]>
          #  src-filter: <value of string>
          #  ssl-algorithm: <value in [high, low, medium, ...]>
          #  ssl-certificate: <value of string>
          #  ssl-client-fallback: <value in [disable, enable]>
          #  ssl-client-renegotiation: <value in [deny, allow, secure]>
          #  ssl-client-session-state-max: <value of integer>
          #  ssl-client-session-state-timeout: <value of integer>
          #  ssl-client-session-state-type: <value in [disable, time, count, ...]>
          #  ssl-dh-bits: <value in [768, 1024, 1536, ...]>
          #  ssl-hpkp: <value in [disable, enable, report-only]>
          #  ssl-hpkp-age: <value of integer>
          #  ssl-hpkp-backup: <value of string>
          #  ssl-hpkp-include-subdomains: <value in [disable, enable]>
          #  ssl-hpkp-primary: <value of string>
          #  ssl-hpkp-report-uri: <value of string>
          #  ssl-hsts: <value in [disable, enable]>
          #  ssl-hsts-age: <value of integer>
          #  ssl-hsts-include-subdomains: <value in [disable, enable]>
          #  ssl-http-location-conversion: <value in [disable, enable]>
          #  ssl-http-match-host: <value in [disable, enable]>
          #  ssl-max-version: <value in [ssl-3.0, tls-1.0, tls-1.1, ...]>
          #  ssl-min-version: <value in [ssl-3.0, tls-1.0, tls-1.1, ...]>
          #  ssl-mode: <value in [half, full]>
          #  ssl-pfs: <value in [require, deny, allow]>
          #  ssl-send-empty-frags: <value in [disable, enable]>
          #  ssl-server-algorithm: <value in [high, low, medium, ...]>
          #  ssl-server-max-version: <value in [ssl-3.0, tls-1.0, tls-1.1, ...]>
          #  ssl-server-min-version: <value in [ssl-3.0, tls-1.0, tls-1.1, ...]>
          #  ssl-server-session-state-max: <value of integer>
          #  ssl-server-session-state-timeout: <value of integer>
          #  ssl-server-session-state-type: <value in [disable, time, count, ...]>
          #  type: <value in [static-nat, server-load-balance]>
          #  uuid: <value of string>
          #  weblogic-server: <value in [disable, enable]>
          #  websphere-server: <value in [disable, enable]>