# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: IPS
# Desc: Retrieve all the IPS sensors
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the IPS sensors
     fmgr_fact:
       facts:
           selector: 'ips_sensor'
           params:
               adom: 'ansible'
               sensor: ''