# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: route
# Desc: Configure identity based routing
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure identity based routing.
     fmgr_firewall_identitybasedroute:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        firewall_identitybasedroute:
           comments: 'ansible-comments'
           name: 'ansible-test'
          #  rule:
          #    -
          #        device: <value of string>
          #        gateway: <value of string>
          #        groups: <value of string>
          #        id: <value of integer>