# Author: Xing Li
# Org: Fortinet
# Date: 2020.10.13
# Label: FortiCarrier
# Desc: Retrieve all the MMS profiles
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the MMS profiles
     fmgr_fact:
       facts:
           selector: 'firewall_mmsprofile'
           params:
               adom: 'FortiCarrier' # FortiCarrier only object, need a FortiCarrier adom
               mms-profile: ''