# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system
# Desc: Log content filters.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Log content filters.
     fmgr_system_logfetch_clientprofile_logfilter:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        client-profile: 1 # id
        state: present
        system_logfetch_clientprofile_logfilter:
           field: 0
           id: 1
           oper: '!=' #<value in [=, !=, <, ...]>
           value: ansible