# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.29
# Label: deamon
# Desc: Delete a device.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Delete a device.
     fmgr_dvm_cmd_del_device:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        dvm_cmd_del_device:
           adom: ansible
           device: ansible-test # device name 
          #  flags:
          #    - none
          #    - create_task
          #    - nonblocking
          #    - log_dev