# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: firewall, IPv4, IPv6
# Desc: Retrieve all the real servers of IPv6 to IPv4 virtual IP
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the real servers of IPv6 to IPv4 virtual IP
     fmgr_fact:
       facts:
           selector: 'firewall_vip64_realservers'
           params:
               adom: 'ansible'
               vip64: 'ansible-test-vip64' # name
               realservers: ''