# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: package, firewall, IPv4
# Desc: Retrieve all the user defined IPv4 local-in policies
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the user defined IPv4 local-in policies
     fmgr_fact:
       facts:
           selector: 'pkg_firewall_localinpolicy'
           params:
               adom: 'ansible'
               pkg: 'ansible' # package name
               local-in-policy: ''