# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: firewall, IPv4
# Desc: Retrieve all the SSL/TLS cipher suites
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the SSL/TLS cipher suites
     fmgr_fact:
       facts:
           selector: 'firewall_vip_sslserverciphersuites'
           params:
               adom: 'ansible'
               vip: 'ansible-test-vip' # name
               ssl-server-cipher-suites: ''