# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: 
# Desc: Retrieve all the server load balancing health monitors
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the server load balancing health monitors
     fmgr_fact:
       facts:
           selector: 'firewall_ldbmonitor'
           params:
               adom: 'ansible'
               ldb-monitor: ''