# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: group
# Desc: Retrieve all the groups in the device

- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the groups in the device
     fmgr_fact:
       facts:
           selector: 'dvmdb_group'
           params:
               adom: 'ansible'
               group: ''