# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.28
# Label: user
# Desc: Configure FortiToken.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure FortiToken.
     fmgr_user_fortitoken:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        user_fortitoken:
           comments: ansible-comment
          #  license: <value of string>
          #  os-ver: <value of string>
          #  reg-id: 2
           serial-number: # need a valid FortiToken serial number
           status: lock #<value in [lock, active]>