# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: DNS
# Desc: Retrieve all the domain filters 

- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the domain filters
     fmgr_fact:
       facts:
           selector: 'dnsfilter_domainfilter'
           params:
               adom: 'ansible'
               domain-filter: ''