# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system
# Desc: Configure replacement message groups.
- hosts: fortimanager00
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure replacement message groups.
     fmgr_system_replacemsggroup:
        bypass_validation: False
        # workspace_locking_adom: <value in [global, custom adom including root]>
        # workspace_locking_timeout: 300
        # rc_succeeded: [0, -2, -3, ...]
        # rc_failed: [-2, -3, ...]
        adom: ansible
        state: present
        system_replacemsggroup:
          #  admin:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  alertmail:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  auth:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
           comment: ansible-comment
          #  custom-message:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  device-detection-portal:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  ec:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  fortiguard-wf:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  ftp:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  group-type: <value in [default, utm, auth, ...]>
          #  http:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  icap:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  mail:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  mm1:
          #    -
          #        add-smil: <value in [disable, enable]>
          #        charset: <value in [us-ascii, utf-8]>
          #        class: <value in [personal, advertisement, information, ...]>
          #        format: <value in [none, text, html, ...]>
          #        from: <value of string>
          #        from-sender: <value in [disable, enable]>
          #        header: <value in [none, http, 8bit]>
          #        image: <value of string>
          #        message: <value of string>
          #        msg-type: <value of string>
          #        priority: <value in [low, normal, high, ...]>
          #        rsp-status: <value in [ok, err-unspecified, err-srv-denied, ...]>
          #        rsp-text: <value of string>
          #        sender-visibility: <value in [hide, show, not-specified]>
          #        smil-part: <value of string>
          #        subject: <value of string>
          #  mm3:
          #    -
          #        add-html: <value in [disable, enable]>
          #        charset: <value in [us-ascii, utf-8]>
          #        format: <value in [none, text, html, ...]>
          #        from: <value of string>
          #        from-sender: <value in [disable, enable]>
          #        header: <value in [none, http, 8bit]>
          #        html-part: <value of string>
          #        image: <value of string>
          #        message: <value of string>
          #        msg-type: <value of string>
          #        priority: <value in [low, normal, high, ...]>
          #        subject: <value of string>
          #  mm4:
          #    -
          #        add-smil: <value in [disable, enable]>
          #        charset: <value in [us-ascii, utf-8]>
          #        class: <value in [personal, advertisement, informational, ...]>
          #        domain: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        from: <value of string>
          #        from-sender: <value in [disable, enable]>
          #        header: <value in [none, http, 8bit]>
          #        image: <value of string>
          #        message: <value of string>
          #        msg-type: <value of string>
          #        priority: <value in [low, normal, high, ...]>
          #        rsp-status: <value in [ok, err-unspecified, err-srv-denied, ...]>
          #        smil-part: <value of string>
          #        subject: <value of string>
          #  mm7:
          #    -
          #        add-smil: <value in [disable, enable]>
          #        addr-type: <value in [rfc2822-addr, number, short-code]>
          #        allow-content-adaptation: <value in [disable, enable]>
          #        charset: <value in [us-ascii, utf-8]>
          #        class: <value in [personal, advertisement, informational, ...]>
          #        format: <value in [none, text, html, ...]>
          #        from: <value of string>
          #        from-sender: <value in [disable, enable]>
          #        header: <value in [none, http, 8bit]>
          #        image: <value of string>
          #        message: <value of string>
          #        msg-type: <value of string>
          #        priority: <value in [low, normal, high, ...]>
          #        rsp-status: <value in [success, partial-success, client-err, ...]>
          #        smil-part: <value of string>
          #        subject: <value of string>
          #  mms:
          #    -
          #        buffer: <value of string>
          #        charset: <value in [us-ascii, utf-8]>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        image: <value of string>
          #        msg-type: <value of string>
          #  nac-quar:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
           name: ansible-test
          #  nntp:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  spam:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  sslvpn:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  traffic-quota:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  utm:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>
          #  webproxy:
          #    -
          #        buffer: <value of string>
          #        format: <value in [none, text, html, ...]>
          #        header: <value in [none, http, 8bit]>
          #        msg-type: <value of string>