# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: system, DHCP
# Desc: Retrieve all the DHCP options of DHCP server
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the DHCP options of DHCP server
     fmgr_fact:
       facts:
           selector: 'system_dhcp_server_options'
           params:
               adom: 'ansible'
               server: '1' # id
               options: ''