# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.24
# Label: internet service
# Desc: Retrieve all the ipranges in the disabled entry
- name: gathering fortimanager facts
  hosts: fortimanager00
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the ipranges in the disabled entry
     fmgr_fact:
       facts:
           selector: 'firewall_internetservicecustom_disableentry_iprange'
           params:
               adom: 'ansible'
               internet-service-custom: 'ansible-test' # name
               disable-entry: '1' # id
               ip-range: ''